<?php
/**
 * @file
 * Supports creating menu links that are local files.
 */

/**
 * Implements hook_menu().
 */
function file_menu_link_menu() {
  // Define a router item for the files directory.
  $items[file_stream_wrapper_get_instance_by_scheme(file_default_scheme())
    ->getDirectoryPath()] = array(
    'page callback' => 'backdrop_not_found',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}
